[titan-194] feat: bumping web vitals
wpengine/atlas-commerce-blueprint pull request #62
Opened 2023-01-25 13:39 UTC by mikepawlinski

This is a couple of changes that overall bumps on average 6-8 performance points in lighthouse mobile score:
- removed fontawesome for rating (less ~ 20kb of gzipped styles), it looks worse, this change gives 2-4 points

| before | after |
|---|---|
| ![Screenshot 2023-01-25 at 14 32 04](https://user-images.githubusercontent.com/91472483/214577370-32ddec34-5603-4cd0-88f6-c8bc2955c08f.png) | ![Screenshot 2023-01-25 at 14 31 55](https://user-images.githubusercontent.com/91472483/214577364-cf0105e0-feca-49bf-ad9a-df45f90269ac.png) |

- added lazyloads to images where possible
- minor style changes to work with https://github.com/wpengine/atlas-commerce-blocks/pull/12 

Overall this PR and the one above gets us ~85 performance score. Removing logo and hero images completely gives us 100 (that means: eventually these images are blocking us, and there is poor chance we can go above without affecting hero block, ie adding another field for mobile image)

2023-01-25 13:45 UTC, mikepawlinski commented on package.json
> +    "@faustwp/cli": "0.2.0",
bumping faust decreased package by ~30kb (looked like something with lodash)

2023-01-25 13:47 UTC, mikepawlinski commented on src/components/Reviews/Review.js
> +              <span style={{display: "none"}}>
hm, this is not exactly the same thing for accessibility, looking into rolling it back

2023-01-25 13:52 UTC, mikepawlinski commented on src/components/Reviews/Review.js
> +              <span style={{display: "none"}}>
rolled back

2023-01-25 13:53 UTC, mikepawlinski commented on src/components/Reviews/Reviews.module.scss
> +          --percent: calc(var(--rating) / 5 * 100%);
https://codepen.io/FredGenkin/pen/eaXYGV

2023-01-25 14:16 UTC, RossoMaguire commented
Just noticed an error where by the descriptions aren't being shown on the product page's when coming from the home page blocks. Could you investigate as part of this PR ? It's happening in demo store as well so it's not from these changes

2023-01-25 14:28 UTC, RossoMaguire requested changes
Just noticed an error where by the descriptions aren't being shown on the product page's when coming from the home page blocks. Could you investigate as part of this PR ?

2023-01-25 15:06 UTC, RossoMaguire commented
> @RossoMaguire do you mind sharing a screenshot? I cannot reproduce it

**From card on home page**
<img width="1357" alt="Screenshot 2023-01-25 at 15 02 27" src="https://user-images.githubusercontent.com/48026075/214598225-94ccbd85-1b36-478c-9a95-0be006c80839.png">


**From card on shop page**
<img width="1298" alt="Screenshot 2023-01-25 at 15 02 49" src="https://user-images.githubusercontent.com/48026075/214598811-120a0083-5177-41e4-af85-4ada5e76f96e.png">

2023-01-26 10:47 UTC, RossoMaguire approved these changes

2023-01-26 12:13 UTC, merged